name: CI to Release

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Maven
      - run: mvn test

  merge-to-release:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' && success() }}

    steps:
      - name: Checking out code
        uses: actions/checkout@v3
        with:
          ref: '*'

      - name: Configuring user for GitHub actions
        run: |
          git fetch origin main
          git checkout main
          git merge --ff-only origin/*
          git push origin main